[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
raydium_puppet = "3kZmRLYfSmV9sYTH7upYwtLGmKkXRRMvoXwQLRnPchm2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

# [test]
# startup_wait = 10000

#[[test.genesis.clone]]
# AMM Program
#address = 675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8
#program = "amm.so"

# [test.validator]
# url = "..."

# [[test.validator.clone]]
# # ATA for mint: 2SiSpNowr7zUv5ZJHuzHszskQNaskWsNukhivCtuVLHo
# address = 'BRJjxcadDgagNrjSeCvVDtr2VcSYtyRGGFWw9CQBVRSb'

# [[test.validator.clone]]
# # ATA for mint: GfmdKWR1KrttDsQkJfwtXovZw9bUBHYkPAEwB6wZqQvJ
# address = 'Ggg6wPwkUfik9biby3CrA7Liw8Ui4Jt6qju7437TtbZo'

# [[test.validator.clone]]
# # USDCMint From DevNet
# address = "9T7uw5dqaEmEC4McqyefzYsEg5hoC4e2oV8it1Uc4f1U"

# [[test.validator.clone]]
# # amm_program
# address = "HWy1jotHpo6UqeQxx49dpYYdQB8wj9Qk9MdxwjLvDHB8"

# [[test.validator.clone]]
# # amm_pool_id USDC POOL_ID
# address = "BbZjQanvSaE9me4adAitmTTaSgASvzaVignt4HRSM7ww"

# [[test.validator.clone]]
# # openbook_program market_program
# address = "EoTcMgcDRTJVZDMZWBoU6rhYHZfkNTVEAfz3uUJRcYGj"

# [[test.validator.clone]]
# # market
# address = "74yqm5ihhMg5XJeqvC6oPsHaczjF6U9Rc8zs4wMnAGUL"

# [[test.validator.clone]]
# # amm_coin_mint
# address = "2SiSpNowr7zUv5ZJHuzHszskQNaskWsNukhivCtuVLHo"

# [[test.validator.clone]]
# # amm_pc_mint
# address = "GfmdKWR1KrttDsQkJfwtXovZw9bUBHYkPAEwB6wZqQvJ"

# [[test.validator.clone]]
# # create_pool_fee_address
# address = "3XMrhbv989VxAMi3DErLV9eJht1pHppW5LbKxe9fkEFR"

# [[test.validator.clone]]
# # input_token_mint
# address = "GfmdKWR1KrttDsQkJfwtXovZw9bUBHYkPAEwB6wZqQvJ"

# [[test.validator.clone]]
# # output_token_mint
# address = "2SiSpNowr7zUv5ZJHuzHszskQNaskWsNukhivCtuVLHo"

